[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "~0.3.17"
regex = "~1.7.0"
log = "~0.4.17"
env_logger = "~0.10.0"
