name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example:
          - hello_world
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v3
      - run: |
          rustup update ${{ matrix.toolchain }} \
          && rustup default ${{ matrix.toolchain }}
        working-directory: ${{ matrix.example }}
      - run: cargo build --verbose
        working-directory: ${{ matrix.example }}
      - run: cargo test --verbose
        working-directory: ${{ matrix.example }}
